name: RuboCop

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  rubocop:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.user.login == 'dependabot[bot]')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install RuboCop
        run: sudo gem install rubocop -v 1.59.0

      - name: Run RuboCop
        run: rubocop ./lib